### PR TITLE
V1.0.2

### PR DESCRIPTION
**Pull request by pjayala**
Release a new version with upgraded dependencies with security fixes.

### CODE REVIEW

**Comment by pjayala** [comment]
Just noticed you have merged updated version of dependencies. This PR is just to release those dependencies as a new version so it can be consumed.

**Comment by rejas** [comment]
hi @JimmyRobz any chance you could release the v1.0.2 via npm? thx in advance

**Comment by jimmy-robert** [comment]
Thanks for the PR, just published the new version, sorry if it took some time but I am not very active in this repository as I don't use it myself anymore.

**Comment by rejas** [comment]
No worries, thanks for the release, happy to have no audit warnings anymore :-D

**Pull request merged**
